import type { Metadata } from 'next';
import './globals.css';
import Navigation from './ui/components/navigation/Navigation';
import SmallScreenNavigation from './ui/components/navigation/SmallScreenNavigation';
import { Socials } from './ui/components/social/Socials';
import FooterSection from './ui/sections/footerSection';
import SmallScreenSocial from './ui/components/social/SmallScreenSocial';

export const metadata: Metadata = {
  title: 'Text task for PopArt',
  description: 'Generated by Bojan Petrovic',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased max-w-7xl mx-auto text-center">
        <Navigation />
        {children}
        <SmallScreenNavigation />
        <Socials />
        <SmallScreenSocial />
        <FooterSection />
      </body>
    </html>
  );
}
